// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/api/config": {
    params: {};
  };
  "/api/auth/register": {
    params: {};
  };
  "/api/auth/login": {
    params: {};
  };
  "/api/auth/me": {
    params: {};
  };
  "/api/auth/logout": {
    params: {};
  };
  "/api/items": {
    params: {};
  };
  "/api/items/:id": {
    params: {
      "id": string;
    };
  };
  "/api/categories": {
    params: {};
  };
  "/api/categories/:id": {
    params: {
      "id": string;
    };
  };
  "/api/storage/presigned-url": {
    params: {};
  };
  "/api/borrowings": {
    params: {};
  };
  "/api/borrowings/active": {
    params: {};
  };
  "/api/borrowings/checkout": {
    params: {};
  };
  "/api/borrowings/:id/checkin": {
    params: {
      "id": string;
    };
  };
  "/api/reports/summary": {
    params: {};
  };
  "/api/reports/history": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/items": {
    params: {};
  };
  "/items/:id": {
    params: {
      "id": string;
    };
  };
  "/scan": {
    params: {};
  };
  "/history": {
    params: {};
  };
  "/admin/items": {
    params: {};
  };
  "/admin/categories": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/api/config" | "/api/auth/register" | "/api/auth/login" | "/api/auth/me" | "/api/auth/logout" | "/api/items" | "/api/items/:id" | "/api/categories" | "/api/categories/:id" | "/api/storage/presigned-url" | "/api/borrowings" | "/api/borrowings/active" | "/api/borrowings/checkout" | "/api/borrowings/:id/checkin" | "/api/reports/summary" | "/api/reports/history" | "/login" | "/register" | "/dashboard" | "/items" | "/items/:id" | "/scan" | "/history" | "/admin/items" | "/admin/categories";
  };
  "routes/api.config.ts": {
    id: "routes/api.config";
    page: "/api/config";
  };
  "routes/api.auth.register.ts": {
    id: "routes/api.auth.register";
    page: "/api/auth/register";
  };
  "routes/api.auth.login.ts": {
    id: "routes/api.auth.login";
    page: "/api/auth/login";
  };
  "routes/api.auth.me.ts": {
    id: "routes/api.auth.me";
    page: "/api/auth/me";
  };
  "routes/api.auth.logout.ts": {
    id: "routes/api.auth.logout";
    page: "/api/auth/logout";
  };
  "routes/api.items.ts": {
    id: "routes/api.items";
    page: "/api/items";
  };
  "routes/api.items.id.ts": {
    id: "routes/api.items.id";
    page: "/api/items/:id";
  };
  "routes/api.categories.ts": {
    id: "routes/api.categories";
    page: "/api/categories";
  };
  "routes/api.categories.id.ts": {
    id: "routes/api.categories.id";
    page: "/api/categories/:id";
  };
  "routes/api.storage.presigned-url.ts": {
    id: "routes/api.storage.presigned-url";
    page: "/api/storage/presigned-url";
  };
  "routes/api.borrowings.ts": {
    id: "routes/api.borrowings";
    page: "/api/borrowings";
  };
  "routes/api.borrowings.active.ts": {
    id: "routes/api.borrowings.active";
    page: "/api/borrowings/active";
  };
  "routes/api.borrowings.checkout.ts": {
    id: "routes/api.borrowings.checkout";
    page: "/api/borrowings/checkout";
  };
  "routes/api.borrowings.checkin.ts": {
    id: "routes/api.borrowings.checkin";
    page: "/api/borrowings/:id/checkin";
  };
  "routes/api.reports.summary.ts": {
    id: "routes/api.reports.summary";
    page: "/api/reports/summary";
  };
  "routes/api.reports.history.ts": {
    id: "routes/api.reports.history";
    page: "/api/reports/history";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/register.tsx": {
    id: "routes/register";
    page: "/register";
  };
  "routes/layout.tsx": {
    id: "routes/layout";
    page: "/dashboard" | "/items" | "/items/:id" | "/scan" | "/history" | "/admin/items" | "/admin/categories";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard";
  };
  "routes/items.tsx": {
    id: "routes/items";
    page: "/items";
  };
  "routes/item-detail.tsx": {
    id: "routes/item-detail";
    page: "/items/:id";
  };
  "routes/scan.tsx": {
    id: "routes/scan";
    page: "/scan";
  };
  "routes/history.tsx": {
    id: "routes/history";
    page: "/history";
  };
  "routes/admin-items.tsx": {
    id: "routes/admin-items";
    page: "/admin/items";
  };
  "routes/admin-categories.tsx": {
    id: "routes/admin-categories";
    page: "/admin/categories";
  };
  "routes/index.tsx": {
    id: "routes/index";
    page: "/";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/api.config": typeof import("./app/routes/api.config.ts");
  "routes/api.auth.register": typeof import("./app/routes/api.auth.register.ts");
  "routes/api.auth.login": typeof import("./app/routes/api.auth.login.ts");
  "routes/api.auth.me": typeof import("./app/routes/api.auth.me.ts");
  "routes/api.auth.logout": typeof import("./app/routes/api.auth.logout.ts");
  "routes/api.items": typeof import("./app/routes/api.items.ts");
  "routes/api.items.id": typeof import("./app/routes/api.items.id.ts");
  "routes/api.categories": typeof import("./app/routes/api.categories.ts");
  "routes/api.categories.id": typeof import("./app/routes/api.categories.id.ts");
  "routes/api.storage.presigned-url": typeof import("./app/routes/api.storage.presigned-url.ts");
  "routes/api.borrowings": typeof import("./app/routes/api.borrowings.ts");
  "routes/api.borrowings.active": typeof import("./app/routes/api.borrowings.active.ts");
  "routes/api.borrowings.checkout": typeof import("./app/routes/api.borrowings.checkout.ts");
  "routes/api.borrowings.checkin": typeof import("./app/routes/api.borrowings.checkin.ts");
  "routes/api.reports.summary": typeof import("./app/routes/api.reports.summary.ts");
  "routes/api.reports.history": typeof import("./app/routes/api.reports.history.ts");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/register": typeof import("./app/routes/register.tsx");
  "routes/layout": typeof import("./app/routes/layout.tsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.tsx");
  "routes/items": typeof import("./app/routes/items.tsx");
  "routes/item-detail": typeof import("./app/routes/item-detail.tsx");
  "routes/scan": typeof import("./app/routes/scan.tsx");
  "routes/history": typeof import("./app/routes/history.tsx");
  "routes/admin-items": typeof import("./app/routes/admin-items.tsx");
  "routes/admin-categories": typeof import("./app/routes/admin-categories.tsx");
  "routes/index": typeof import("./app/routes/index.tsx");
};